### ISSUE TITLE
Er komen op de pagina 2 soorten meer-knoppen voor / mankerende navbar

### ISSUE THREAD

**Issue by Theo-denBlanken** [MeesPos/BEM_FRO#3]
Je wenst ze verschillend vorm te geven. Daar kun je dus modifiers voor gebruiken.
Geef er daarom er 1 een modifier.
In de navbar (die niet te zien is, los dit nog even op graag) staat een actieve link:
`a href="#" class="navbar__link navbar__actief">Home</a>` ook een mooi voorbeeld van een mogelijkheid een modifier in te zetten, maar dan wel zo: 
`<a href="#" class="navbar__link navbar--actief">Home</a>`

**Comment by MeesPos** [comment]
Is gefixed
